#!/usr/bin/env ruby

if ENV['VO_DEBUGGING']
  require_relative '../lib/nugem'
else
  require 'nugem'
end

module Nugem
  def self.positional_parameters
    ARGV.reject { |x| x.start_with? '-' }
  end

  def self.run_me
    pp = ::Nugem.positional_parameters
    help if pp.empty?
    gem_type = pp.first
    case gem_type
    when 'gem'
      nugem = Nugem::Options.new
      nugem.parse_options
    when 'jekyll'
      nugem = Nugem::JekyllOptions.new
      nugem.parse_options
    else
      puts "Error: unrecognized gem type '#{gem_type}'."
      exit 2
    end
  end
end

Nugem.run_me
